[package]
name = "upt"
version = "0.1.3"
authors = ["sigoden <sigoden@gmail.com>"]
edition = "2018"
description = "Universal package management tool for Windows, MacOS, Linux"
documentation = "https://github.com/sigoden/upt"
repository = "https://github.com/sigoden/upt"
keywords = ["universal", "package", "management"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"

[[bin]]
doc = false
name = "upt"

[badges]
travis-ci = { repository = "sigoden/upt" }
appveyor = { repository = "sigoden/upt" }
